CREATE TABLE IF NOT EXISTS arrest_warrants (
    id INT AUTO_INCREMENT PRIMARY KEY,
    warrant_number VARCHAR(30) NOT NULL UNIQUE,
    case_number VARCHAR(30) NOT NULL UNIQUE,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    other_names VARCHAR(100) NULL,
    date_of_birth DATE NOT NULL,
    gender VARCHAR(10) NOT NULL,
    nationality VARCHAR(50) NOT NULL,
    national_id VARCHAR(50) NULL,
    offense VARCHAR(100) NOT NULL,
    offense_description TEXT NULL,
    arrest_date DATE NOT NULL,
    arresting_officer VARCHAR(100) NOT NULL,
    arresting_agency VARCHAR(100) NOT NULL,
    court VARCHAR(100) NOT NULL,
    judge VARCHAR(100) NULL,
    sentence_type VARCHAR(30) NOT NULL,
    sentence_duration VARCHAR(50) NULL,
    status VARCHAR(20) NOT NULL,
    issued_date DATE NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT chk_arrest_warrants_gender CHECK (gender IN ('male', 'female')),
    CONSTRAINT chk_arrest_warrants_sentence_type CHECK (sentence_type IN ('remand', 'convicted', 'life', 'death')),
    CONSTRAINT chk_arrest_warrants_status CHECK (status IN ('pending', 'executed', 'cancelled')),
    INDEX idx_arrest_warrants_warrant_number (warrant_number),
    INDEX idx_arrest_warrants_case_number (case_number),
    INDEX idx_arrest_warrants_first_name (first_name),
    INDEX idx_arrest_warrants_last_name (last_name),
    INDEX idx_arrest_warrants_national_id (national_id),
    INDEX idx_arrest_warrants_offense (offense),
    INDEX idx_arrest_warrants_arrest_date (arrest_date),
    INDEX idx_arrest_warrants_status (status),
    INDEX idx_arrest_warrants_sentence_type (sentence_type),
    INDEX idx_arrest_warrants_issued_date (issued_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
