CREATE TABLE IF NOT EXISTS inmates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    inmate_id VARCHAR(20) NOT NULL UNIQUE,
    warrant_id INT NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    other_names VARCHAR(100) NULL,
    date_of_birth DATE NOT NULL,
    age INT NOT NULL,
    gender VARCHAR(10) NOT NULL,
    nationality VARCHAR(50) NOT NULL,
    national_id VARCHAR(50) NULL,
    phone VARCHAR(20) NULL,
    address TEXT NULL,
    marital_status VARCHAR(20) NOT NULL,
    photo VARCHAR(255) NULL,
    fingerprint_id VARCHAR(50) NULL UNIQUE,
    height_cm DECIMAL(5,1) NULL,
    weight_kg DECIMAL(5,1) NULL,
    eye_color VARCHAR(20) NULL,
    hair_color VARCHAR(20) NULL,
    distinguishing_marks TEXT NULL,
    religion VARCHAR(50) NULL,
    occupation VARCHAR(100) NULL,
    education_level VARCHAR(50) NULL,
    next_of_kin_name VARCHAR(100) NOT NULL,
    next_of_kin_relation VARCHAR(30) NOT NULL,
    next_of_kin_contact VARCHAR(20) NULL,
    next_of_kin_address TEXT NULL,
    case_number VARCHAR(30) NOT NULL,
    offense VARCHAR(100) NOT NULL,
    offense_description TEXT NULL,
    arrest_date DATE NOT NULL,
    arresting_officer VARCHAR(100) NOT NULL,
    arresting_agency VARCHAR(100) NOT NULL,
    court VARCHAR(100) NOT NULL,
    judge VARCHAR(100) NULL,
    sentence_type VARCHAR(30) NOT NULL,
    sentence_duration VARCHAR(50) NULL,
    expected_release_date DATE NULL,
    status VARCHAR(20) NOT NULL,
    admission_date DATE NOT NULL,
    admission_time TIME NOT NULL,
    admission_officer_id INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_inmates_warrant_id
        FOREIGN KEY (warrant_id) REFERENCES arrest_warrants(id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_inmates_admission_officer_id
        FOREIGN KEY (admission_officer_id) REFERENCES users(id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_inmates_age CHECK (age >= 0),
    CONSTRAINT chk_inmates_gender CHECK (gender IN ('male', 'female')),
    CONSTRAINT chk_inmates_marital_status CHECK (marital_status IN ('single', 'married', 'divorced', 'widowed')),
    CONSTRAINT chk_inmates_next_of_kin_relation CHECK (next_of_kin_relation IN ('spouse', 'parent', 'sibling', 'child', 'other')),
    CONSTRAINT chk_inmates_sentence_type CHECK (sentence_type IN ('remand', 'convicted', 'life', 'death')),
    CONSTRAINT chk_inmates_status CHECK (status IN ('active', 'released', 'transferred', 'deceased')),
    CONSTRAINT chk_inmates_release_after_admission CHECK (expected_release_date IS NULL OR expected_release_date >= admission_date),
    CONSTRAINT chk_inmates_arrest_before_admission CHECK (arrest_date <= admission_date),
    INDEX idx_inmates_inmate_id (inmate_id),
    INDEX idx_inmates_warrant_id (warrant_id),
    INDEX idx_inmates_first_name (first_name),
    INDEX idx_inmates_last_name (last_name),
    INDEX idx_inmates_case_number (case_number),
    INDEX idx_inmates_offense (offense),
    INDEX idx_inmates_status (status),
    INDEX idx_inmates_sentence_type (sentence_type),
    INDEX idx_inmates_gender (gender),
    INDEX idx_inmates_nationality (nationality),
    INDEX idx_inmates_admission_date (admission_date),
    INDEX idx_inmates_arrest_date (arrest_date),
    INDEX idx_inmates_admission_officer_id (admission_officer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inmate_transfers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    inmate_id INT NOT NULL,
    current_facility VARCHAR(150) NOT NULL,
    destination_facility VARCHAR(150) NOT NULL,
    transfer_type VARCHAR(40) NOT NULL,
    reason TEXT NOT NULL,
    security_level VARCHAR(50) NOT NULL,
    medical_clearance BOOLEAN NOT NULL DEFAULT FALSE,
    legal_verified BOOLEAN NOT NULL DEFAULT FALSE,
    security_assessed BOOLEAN NOT NULL DEFAULT FALSE,
    transfer_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    urgency_level VARCHAR(30) NOT NULL,
    requested_date DATE NOT NULL,
    departure_date DATE NULL,
    arrival_date DATE NULL,
    escort_officers TEXT NULL,
    transport_vehicle VARCHAR(100) NULL,
    route_details TEXT NULL,
    movement_authorized_by INT NULL,
    approved_by INT NULL,
    receiving_officer VARCHAR(100) NULL,
    receiving_confirmation BOOLEAN NOT NULL DEFAULT FALSE,
    transfer_completion_notes TEXT NULL,
    created_by INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_inmate_transfers_inmate_id
        FOREIGN KEY (inmate_id) REFERENCES inmates(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_inmate_transfers_movement_authorized_by
        FOREIGN KEY (movement_authorized_by) REFERENCES users(id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_inmate_transfers_approved_by
        FOREIGN KEY (approved_by) REFERENCES users(id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_inmate_transfers_created_by
        FOREIGN KEY (created_by) REFERENCES users(id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_inmate_transfers_type CHECK (transfer_type IN ('INTERNAL_TRANSFER', 'INTER_PRISON_TRANSFER', 'MEDICAL_TRANSFER', 'COURT_TRANSFER', 'REHABILITATION_TRANSFER', 'EMERGENCY_TRANSFER')),
    CONSTRAINT chk_inmate_transfers_status CHECK (transfer_status IN ('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'IN_TRANSIT', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT chk_inmate_transfers_dates CHECK (
        (departure_date IS NULL OR departure_date >= requested_date)
        AND (arrival_date IS NULL OR departure_date IS NOT NULL)
        AND (arrival_date IS NULL OR arrival_date >= departure_date)
    ),
    INDEX idx_inmate_transfers_inmate_id (inmate_id),
    INDEX idx_inmate_transfers_type (transfer_type),
    INDEX idx_inmate_transfers_status (transfer_status),
    INDEX idx_inmate_transfers_current_facility (current_facility),
    INDEX idx_inmate_transfers_destination_facility (destination_facility),
    INDEX idx_inmate_transfers_requested_date (requested_date),
    INDEX idx_inmate_transfers_departure_date (departure_date),
    INDEX idx_inmate_transfers_arrival_date (arrival_date),
    INDEX idx_inmate_transfers_approved_by (approved_by),
    INDEX idx_inmate_transfers_created_by (created_by)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inmate_releases (
    id INT AUTO_INCREMENT PRIMARY KEY,
    inmate_id INT NOT NULL,
    release_type VARCHAR(40) NOT NULL,
    release_reason TEXT NOT NULL,
    sentence_validated BOOLEAN NOT NULL DEFAULT FALSE,
    legal_verified BOOLEAN NOT NULL DEFAULT FALSE,
    medical_cleared BOOLEAN NOT NULL DEFAULT FALSE,
    property_cleared BOOLEAN NOT NULL DEFAULT FALSE,
    identity_verified BOOLEAN NOT NULL DEFAULT FALSE,
    release_certificate_number VARCHAR(100) NULL,
    approved_by INT NULL,
    release_date DATE NULL,
    release_time TIME NULL,
    release_status VARCHAR(30) NOT NULL DEFAULT 'PENDING_REVIEW',
    discharge_notes TEXT NULL,
    property_release_notes TEXT NULL,
    medical_discharge_summary TEXT NULL,
    created_by INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_inmate_releases_inmate_id
        FOREIGN KEY (inmate_id) REFERENCES inmates(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_inmate_releases_approved_by
        FOREIGN KEY (approved_by) REFERENCES users(id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_inmate_releases_created_by
        FOREIGN KEY (created_by) REFERENCES users(id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_inmate_releases_type CHECK (release_type IN ('SENTENCE_COMPLETION', 'BAIL_RELEASE', 'PAROLE', 'PRESIDENTIAL_PARDON', 'MEDICAL_RELEASE', 'COURT_ACQUITTAL')),
    CONSTRAINT chk_inmate_releases_status CHECK (release_status IN ('PENDING_REVIEW', 'LEGAL_VERIFICATION', 'APPROVED', 'REJECTED', 'READY_FOR_RELEASE', 'RELEASED')),
    INDEX idx_inmate_releases_inmate_id (inmate_id),
    INDEX idx_inmate_releases_type (release_type),
    INDEX idx_inmate_releases_status (release_status),
    INDEX idx_inmate_releases_release_date (release_date),
    INDEX idx_inmate_releases_approved_by (approved_by),
    INDEX idx_inmate_releases_created_by (created_by),
    INDEX idx_inmate_releases_certificate (release_certificate_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
