CREATE TABLE IF NOT EXISTS inmates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    inmate_id VARCHAR(20) NOT NULL UNIQUE,
    warrant_id INT NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    other_names VARCHAR(100) NULL,
    date_of_birth DATE NOT NULL,
    age INT NOT NULL,
    gender VARCHAR(10) NOT NULL,
    nationality VARCHAR(50) NOT NULL,
    national_id VARCHAR(50) NULL,
    phone VARCHAR(20) NULL,
    address TEXT NULL,
    marital_status VARCHAR(20) NOT NULL,
    photo VARCHAR(255) NULL,
    fingerprint_id VARCHAR(50) NULL UNIQUE,
    height_cm DECIMAL(5,1) NULL,
    weight_kg DECIMAL(5,1) NULL,
    eye_color VARCHAR(20) NULL,
    hair_color VARCHAR(20) NULL,
    distinguishing_marks TEXT NULL,
    religion VARCHAR(50) NULL,
    occupation VARCHAR(100) NULL,
    education_level VARCHAR(50) NULL,
    next_of_kin_name VARCHAR(100) NOT NULL,
    next_of_kin_relation VARCHAR(30) NOT NULL,
    next_of_kin_contact VARCHAR(20) NULL,
    next_of_kin_address TEXT NULL,
    case_number VARCHAR(30) NOT NULL,
    offense VARCHAR(100) NOT NULL,
    offense_description TEXT NULL,
    arrest_date DATE NOT NULL,
    arresting_officer VARCHAR(100) NOT NULL,
    arresting_agency VARCHAR(100) NOT NULL,
    court VARCHAR(100) NOT NULL,
    judge VARCHAR(100) NULL,
    sentence_type VARCHAR(30) NOT NULL,
    sentence_duration VARCHAR(50) NULL,
    expected_release_date DATE NULL,
    status VARCHAR(20) NOT NULL,
    admission_date DATE NOT NULL,
    admission_time TIME NOT NULL,
    admission_officer_id INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_inmates_warrant_id
        FOREIGN KEY (warrant_id) REFERENCES arrest_warrants(id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_inmates_admission_officer_id
        FOREIGN KEY (admission_officer_id) REFERENCES users(id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_inmates_age CHECK (age >= 0),
    CONSTRAINT chk_inmates_gender CHECK (gender IN ('male', 'female')),
    CONSTRAINT chk_inmates_marital_status CHECK (marital_status IN ('single', 'married', 'divorced', 'widowed')),
    CONSTRAINT chk_inmates_next_of_kin_relation CHECK (next_of_kin_relation IN ('spouse', 'parent', 'sibling', 'child', 'other')),
    CONSTRAINT chk_inmates_sentence_type CHECK (sentence_type IN ('remand', 'convicted', 'life', 'death')),
    CONSTRAINT chk_inmates_status CHECK (status IN ('active', 'released', 'transferred', 'deceased')),
    CONSTRAINT chk_inmates_release_after_admission CHECK (expected_release_date IS NULL OR expected_release_date >= admission_date),
    CONSTRAINT chk_inmates_arrest_before_admission CHECK (arrest_date <= admission_date),
    INDEX idx_inmates_inmate_id (inmate_id),
    INDEX idx_inmates_warrant_id (warrant_id),
    INDEX idx_inmates_first_name (first_name),
    INDEX idx_inmates_last_name (last_name),
    INDEX idx_inmates_case_number (case_number),
    INDEX idx_inmates_offense (offense),
    INDEX idx_inmates_status (status),
    INDEX idx_inmates_sentence_type (sentence_type),
    INDEX idx_inmates_gender (gender),
    INDEX idx_inmates_nationality (nationality),
    INDEX idx_inmates_admission_date (admission_date),
    INDEX idx_inmates_arrest_date (arrest_date),
    INDEX idx_inmates_admission_officer_id (admission_officer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
