CREATE TABLE IF NOT EXISTS vocational_training_enrollments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    inmate_id INT NOT NULL,
    program_name VARCHAR(100) NOT NULL,
    skill_category VARCHAR(100) NOT NULL,
    training_center VARCHAR(120) NOT NULL,
    instructor_name VARCHAR(120) NOT NULL,
    enrollment_date DATE NOT NULL,
    completion_status VARCHAR(30) NOT NULL,
    progress_percentage DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    assessment_score DECIMAL(5,2) NULL,
    certification_eligible BOOLEAN NOT NULL DEFAULT FALSE,
    created_by INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_vocational_training_inmate_id FOREIGN KEY (inmate_id) REFERENCES inmates(id),
    CONSTRAINT fk_vocational_training_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT chk_vocational_program_name CHECK (program_name IN ('Carpentry', 'Welding', 'Tailoring', 'Agriculture', 'ICT Training', 'Plumbing', 'Electrical Installation', 'Art & Craft')),
    CONSTRAINT chk_vocational_completion_status CHECK (completion_status IN ('ENROLLED', 'IN_PROGRESS', 'COMPLETED', 'WITHDRAWN')),
    CONSTRAINT chk_vocational_progress_percentage CHECK (progress_percentage >= 0 AND progress_percentage <= 100),
    CONSTRAINT chk_vocational_assessment_score CHECK (assessment_score IS NULL OR (assessment_score >= 0 AND assessment_score <= 100)),
    INDEX idx_vocational_inmate_id (inmate_id),
    INDEX idx_vocational_program_name (program_name),
    INDEX idx_vocational_completion_status (completion_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS counseling_sessions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    inmate_id INT NOT NULL,
    counselor_name VARCHAR(120) NOT NULL,
    session_type VARCHAR(50) NOT NULL,
    session_date DATE NOT NULL,
    session_notes TEXT NOT NULL,
    behavioral_observation TEXT NOT NULL,
    risk_level VARCHAR(20) NOT NULL,
    follow_up_required BOOLEAN NOT NULL DEFAULT FALSE,
    created_by INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_counseling_sessions_inmate_id FOREIGN KEY (inmate_id) REFERENCES inmates(id),
    CONSTRAINT fk_counseling_sessions_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT chk_counseling_session_type CHECK (session_type IN ('Individual Counseling', 'Group Therapy', 'Trauma Counseling', 'Addiction Recovery', 'Anger Management')),
    CONSTRAINT chk_counseling_risk_level CHECK (risk_level IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    INDEX idx_counseling_inmate_id (inmate_id),
    INDEX idx_counseling_session_date (session_date),
    INDEX idx_counseling_risk_level (risk_level)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS behavioral_assessments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    inmate_id INT NOT NULL,
    behavior_score DECIMAL(5,2) NOT NULL,
    behavior_category VARCHAR(20) NOT NULL,
    observation_notes TEXT NOT NULL,
    incident_count INT NOT NULL DEFAULT 0,
    improvement_level VARCHAR(50) NOT NULL,
    assessed_by INT NOT NULL,
    assessment_date DATE NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_behavioral_assessments_inmate_id FOREIGN KEY (inmate_id) REFERENCES inmates(id),
    CONSTRAINT fk_behavioral_assessments_assessed_by FOREIGN KEY (assessed_by) REFERENCES users(id),
    CONSTRAINT chk_behavior_score CHECK (behavior_score >= 0 AND behavior_score <= 100),
    CONSTRAINT chk_behavior_category CHECK (behavior_category IN ('Excellent', 'Good', 'Fair', 'Poor', 'Violent')),
    CONSTRAINT chk_behavior_incident_count CHECK (incident_count >= 0),
    INDEX idx_behavioral_inmate_id (inmate_id),
    INDEX idx_behavioral_category (behavior_category),
    INDEX idx_behavioral_assessment_date (assessment_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS religious_participations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    inmate_id INT NOT NULL,
    religion VARCHAR(80) NOT NULL,
    activity_type VARCHAR(50) NOT NULL,
    participation_date DATE NOT NULL,
    attendance_status VARCHAR(30) NOT NULL,
    religious_leader VARCHAR(120) NOT NULL,
    notes TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_religious_participations_inmate_id FOREIGN KEY (inmate_id) REFERENCES inmates(id),
    CONSTRAINT chk_religious_activity_type CHECK (activity_type IN ('Church Service', 'Islamic Prayer Session', 'Bible Study', 'Quran Study', 'Spiritual Counseling')),
    CONSTRAINT chk_religious_attendance_status CHECK (attendance_status IN ('REGISTERED', 'ATTENDED', 'MISSED')),
    INDEX idx_religious_inmate_id (inmate_id),
    INDEX idx_religious_activity_type (activity_type),
    INDEX idx_religious_participation_date (participation_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS work_assignments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    inmate_id INT NOT NULL,
    work_type VARCHAR(60) NOT NULL,
    assignment_location VARCHAR(120) NOT NULL,
    supervisor_name VARCHAR(120) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NULL,
    performance_rating DECIMAL(5,2) NULL,
    attendance_record TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_work_assignments_inmate_id FOREIGN KEY (inmate_id) REFERENCES inmates(id),
    CONSTRAINT chk_work_type CHECK (work_type IN ('Kitchen Duties', 'Farming', 'Cleaning Services', 'Maintenance Work', 'Construction Assistance')),
    CONSTRAINT chk_work_performance_rating CHECK (performance_rating IS NULL OR (performance_rating >= 0 AND performance_rating <= 100)),
    CONSTRAINT chk_work_date_order CHECK (end_date IS NULL OR end_date >= start_date),
    INDEX idx_work_assignments_inmate_id (inmate_id),
    INDEX idx_work_assignments_work_type (work_type),
    INDEX idx_work_assignments_start_date (start_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS skill_certifications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    inmate_id INT NOT NULL,
    certification_name VARCHAR(120) NOT NULL,
    skill_area VARCHAR(100) NOT NULL,
    issuing_authority VARCHAR(120) NOT NULL,
    issue_date DATE NOT NULL,
    certificate_number VARCHAR(80) NOT NULL UNIQUE,
    grade VARCHAR(30) NOT NULL,
    validity_status VARCHAR(30) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_skill_certifications_inmate_id FOREIGN KEY (inmate_id) REFERENCES inmates(id),
    CONSTRAINT chk_skill_certification_grade CHECK (grade IN ('Basic', 'Intermediate', 'Advanced', 'Professional')),
    CONSTRAINT chk_skill_certification_validity CHECK (validity_status IN ('VALID', 'EXPIRED', 'REVOKED')),
    INDEX idx_skill_certifications_inmate_id (inmate_id),
    INDEX idx_skill_certifications_skill_area (skill_area),
    INDEX idx_skill_certifications_issue_date (issue_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS post_release_followups (
    id INT AUTO_INCREMENT PRIMARY KEY,
    inmate_id INT NOT NULL,
    release_date DATE NOT NULL,
    follow_up_date DATE NOT NULL,
    employment_status VARCHAR(80) NOT NULL,
    housing_status VARCHAR(80) NOT NULL,
    reintegration_score DECIMAL(5,2) NOT NULL,
    recidivism_risk_level VARCHAR(20) NOT NULL,
    notes TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_post_release_followups_inmate_id FOREIGN KEY (inmate_id) REFERENCES inmates(id),
    CONSTRAINT chk_post_release_reintegration_score CHECK (reintegration_score >= 0 AND reintegration_score <= 100),
    CONSTRAINT chk_post_release_risk_level CHECK (recidivism_risk_level IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT chk_post_release_followup_date CHECK (follow_up_date >= release_date),
    INDEX idx_post_release_inmate_id (inmate_id),
    INDEX idx_post_release_follow_up_date (follow_up_date),
    INDEX idx_post_release_risk_level (recidivism_risk_level)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
