CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    officer_id VARCHAR(20) NOT NULL UNIQUE,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    badge_number VARCHAR(30) NOT NULL UNIQUE,
    `rank` VARCHAR(50) NOT NULL,
    department VARCHAR(50) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'officer',
    shift VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    date_joined DATE NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT chk_users_role CHECK (role IN ('admin', 'officer', 'supervisor', 'medical_officer', 'records_officer', 'visitor_officer')),
    CONSTRAINT chk_users_shift CHECK (shift IN ('morning', 'afternoon', 'night')),
    CONSTRAINT chk_users_status CHECK (status IN ('active', 'inactive', 'suspended')),
    INDEX idx_users_officer_id (officer_id),
    INDEX idx_users_email (email),
    INDEX idx_users_badge_number (badge_number),
    INDEX idx_users_role (role),
    INDEX idx_users_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
