CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    officer_id VARCHAR(20) NOT NULL UNIQUE,
    first_name VARCHAR(50) NOT NULL,
    middle_name VARCHAR(50),
    last_name VARCHAR(50) NOT NULL,
    gender VARCHAR(20),
    dob DATE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    national_id VARCHAR(50),
    address TEXT,
    profile_image VARCHAR(255),
    staff_id VARCHAR(50),
    badge_number VARCHAR(30) NOT NULL UNIQUE,
    `rank` VARCHAR(50) NOT NULL,
    department VARCHAR(50) NOT NULL,
    position VARCHAR(100),
    employment_date DATE,
    branch VARCHAR(100),
    username VARCHAR(100),
    role_id INT,
    role VARCHAR(20) NOT NULL DEFAULT 'officer',
    shift VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    date_joined DATE NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT chk_users_role CHECK (role IN ('admin', 'officer', 'supervisor', 'medical_officer', 'records_officer', 'visitor_officer', 'security_officer', 'warden', 'accountant', 'store_keeper', 'chaplain', 'cook', 'driver', 'cleaner', 'gardener')),
    CONSTRAINT chk_users_shift CHECK (shift IN ('morning', 'afternoon', 'night')),
    CONSTRAINT chk_users_status CHECK (status IN ('active', 'inactive', 'suspended')),
    INDEX idx_users_officer_id (officer_id),
    INDEX idx_users_first_name (first_name),
    INDEX idx_users_email (email),
    INDEX idx_users_national_id (national_id),
    INDEX idx_users_staff_id (staff_id),
    INDEX idx_users_badge_number (badge_number),
    INDEX idx_users_last_name (last_name),
    INDEX idx_users_username (username),
    INDEX idx_users_role_id (role_id),
    INDEX idx_users_role (role),
    INDEX idx_users_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
